/*
======================================================================
Creates a Stored Procedure: Load Gold Benchmarks
======================================================================
   This script creates a stored procedure to load the 'gold.fact_positional_benchmarks'
   and 'gold.fact_gk_benchmarks' table. This is an AGGREGATE table that materializes complex window functions
   (Percentiles, Medians) to ensure high performance for downstream BI tools.
   
   Logic:
    - Checks if the target table exists. If not, it auto-generates the schema.
    - TRUNCATES the table (Full Refresh of current benchmarks).
    - INSERTS calculated stats using Window Functions.

   Example: EXECUTE gold.load_gold;
======================================================================
*/

CREATE OR ALTER PROCEDURE gold.load_gold AS
BEGIN
    DECLARE @start_time DATETIME, @end_time DATETIME, @batch_start_time DATETIME, @batch_end_time DATETIME;
    BEGIN TRY
        SET @batch_start_time = GETDATE();
        PRINT '===================================================';
        PRINT 'LOADING GOLD LAYER';
        PRINT '===================================================';

--GOLD.FACT_POSITIONAL_BENCHMARKS
        PRINT '=============================================';
        PRINT 'GOLD.FACT_POSITIONAL_BENCHMARKS';
        PRINT '---------------------------------------------';
        PRINT 'LOADING DATA FROM: silver.fact_outfield_player_stats';
        PRINT 'LOADING DATA FROM: silver.dim_player_info';
        PRINT 'LOADING DATA FROM: silver.dim_team_info';
        PRINT '---------------------------------------------';
        SET @start_time = GETDATE();
        IF OBJECT_ID('gold.fact_positional_benchmarks', 'U') IS NULL
        PRINT '>>> Target table does not exist. Auto-generating schema...';
        SELECT TOP 0 
            A.team_key,
            A.league,
            A.club_name,
            C.position,
            CAST(0 AS INT) as total_minutes_played,
            CAST(0 AS DECIMAL(10,2)) as mean_minutes_played,
            CAST(0 AS DECIMAL(10,2)) as p25_minutes_played,
            CAST(0 AS DECIMAL(10,2)) as median_minutes_played,
            CAST(0 AS DECIMAL(10,2)) as p75_minutes_played,
            CAST(0 AS DECIMAL(10,2)) as total_team_goals_scored_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_team_goals_scored_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_team_goals_scored_per90,
            CAST(0 AS DECIMAL(10,2)) as median_team_goals_scored_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_team_goals_scored_per90,
            CAST(0 AS DECIMAL(10,2)) as total_team_goals_conceded_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_team_goals_conceded_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_team_goals_conceded_per90,
            CAST(0 AS DECIMAL(10,2)) as median_team_goals_conceded_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_team_goals_conceded_per90,
            CAST(0 AS INT) as total_goals,
            CAST(0 AS DECIMAL(10,2)) as mean_goals,
            CAST(0 AS DECIMAL(10,2)) as p25_goals,
            CAST(0 AS DECIMAL(10,2)) as median_goals,
            CAST(0 AS DECIMAL(10,2)) as p75_goals,
            CAST(0 AS INT) as total_goals_outside_the_box,
            CAST(0 AS DECIMAL(10,2)) as mean_goals_outside_the_box,
            CAST(0 AS DECIMAL(10,2)) as p25_goals_outside_the_box,
            CAST(0 AS DECIMAL(10,2)) as median_goals_outside_the_box,
            CAST(0 AS DECIMAL(10,2)) as p75_goals_outside_the_box,
            CAST(0 AS DECIMAL(10,2)) as total_shots_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_shots_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_shots_per90,
            CAST(0 AS DECIMAL(10,2)) as median_shots_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_shots_per90,
            CAST(0 AS DECIMAL(10,2)) as total_xGoals_per_shot,
            CAST(0 AS DECIMAL(10,2)) as mean_xGoals_per_shot,
            CAST(0 AS DECIMAL(10,2)) as p25_xGoals_per_shot,
            CAST(0 AS DECIMAL(10,2)) as median_xGoals_per_shot,
            CAST(0 AS DECIMAL(10,2)) as p75_xGoals_per_shot,
            CAST(0 AS DECIMAL(10,2)) as total_shot_accuracy,
            CAST(0 AS DECIMAL(10,2)) as mean_shot_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p25_shot_accuracy,
            CAST(0 AS DECIMAL(10,2)) as median_shot_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p75_shot_accuracy,
            CAST(0 AS DECIMAL(10,2)) as total_shots_on_target_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_shots_on_target_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_shots_on_target_per90,
            CAST(0 AS DECIMAL(10,2)) as median_shots_on_target_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_shots_on_target_per90,
            CAST(0 AS DECIMAL(10,2)) as total_shots_outside_the_box_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_shots_outside_the_box_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_shots_outside_the_box_per90,
            CAST(0 AS DECIMAL(10,2)) as median_shots_outside_the_box_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_shots_outside_the_box_per90,
            CAST(0 AS DECIMAL(10,2)) as total_goals_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_goals_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_goals_per90,
            CAST(0 AS DECIMAL(10,2)) as median_goals_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_goals_per90,
            CAST(0 AS DECIMAL(10,2)) as total_xGoals_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_xGoals_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_xGoals_per90,
            CAST(0 AS DECIMAL(10,2)) as median_xGoals_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_xGoals_per90,
            CAST(0 AS DECIMAL(10,2)) as total_non_penalty_xGoals_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_non_penalty_xGoals_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_non_penalty_xGoals_per90,
            CAST(0 AS DECIMAL(10,2)) as median_non_penalty_xGoals_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_non_penalty_xGoals_per90,
            CAST(0 AS DECIMAL(10,2)) as total_xGoals_overperformance,
            CAST(0 AS DECIMAL(10,2)) as mean_xGoals_overperformance,
            CAST(0 AS DECIMAL(10,2)) as p25_xGoals_overperformance,
            CAST(0 AS DECIMAL(10,2)) as median_xGoals_overperformance,
            CAST(0 AS DECIMAL(10,2)) as p75_xGoals_overperformance,
            CAST(0 AS DECIMAL(10,2)) as total_conversion_rate,
            CAST(0 AS DECIMAL(10,2)) as mean_conversion_rate,
            CAST(0 AS DECIMAL(10,2)) as p25_conversion_rate,
            CAST(0 AS DECIMAL(10,2)) as median_conversion_rate,
            CAST(0 AS DECIMAL(10,2)) as p75_conversion_rate,
            CAST(0 AS INT) as total_assists,
            CAST(0 AS DECIMAL(10,2)) as mean_assists,
            CAST(0 AS DECIMAL(10,2)) as p25_assists,
            CAST(0 AS DECIMAL(10,2)) as median_assists,
            CAST(0 AS DECIMAL(10,2)) as p75_assists,
            CAST(0 AS DECIMAL(10,2)) as total_assists_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_assists_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_assists_per90,
            CAST(0 AS DECIMAL(10,2)) as median_assists_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_assists_per90,
            CAST(0 AS DECIMAL(10,2)) as total_passes_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_passes_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_passes_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as median_passes_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_passes_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as total_pass_accuracy,
            CAST(0 AS DECIMAL(10,2)) as mean_pass_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p25_pass_accuracy,
            CAST(0 AS DECIMAL(10,2)) as median_pass_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p75_pass_accuracy,
            CAST(0 AS DECIMAL(10,2)) as total_xAssits_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_xAssits_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_xAssits_per90,
            CAST(0 AS DECIMAL(10,2)) as median_xAssits_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_xAssits_per90,
            CAST(0 AS DECIMAL(10,2)) as total_open_play_key_passes_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_open_play_key_passes_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_open_play_key_passes_per90,
            CAST(0 AS DECIMAL(10,2)) as median_open_play_key_passes_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_open_play_key_passes_per90,
            CAST(0 AS DECIMAL(10,2)) as total_chances_created_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_chances_created_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_chances_created_per90,
            CAST(0 AS DECIMAL(10,2)) as median_chances_created_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_chances_created_per90,
            CAST(0 AS DECIMAL(10,2)) as total_dribbles_made_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_dribbles_made_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_dribbles_made_per90,
            CAST(0 AS DECIMAL(10,2)) as median_dribbles_made_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_dribbles_made_per90,
            CAST(0 AS DECIMAL(10,2)) as total_progressive_passes_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_progressive_passes_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_progressive_passes_per90,
            CAST(0 AS DECIMAL(10,2)) as median_progressive_passes_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_progressive_passes_per90,
            CAST(0 AS DECIMAL(10,2)) as total_open_play_crosses_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_open_play_crosses_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_open_play_crosses_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as median_open_play_crosses_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_open_play_crosses_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as total_open_play_cross_accuracy,
            CAST(0 AS DECIMAL(10,2)) as mean_open_play_cross_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p25_open_play_cross_accuracy,
            CAST(0 AS DECIMAL(10,2)) as median_open_play_cross_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p75_open_play_cross_accuracy,
            CAST(0 AS DECIMAL(10,2)) as total_crosses_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_crosses_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_crosses_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as median_crosses_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_crosses_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as total_cross_accuracy,
            CAST(0 AS DECIMAL(10,2)) as mean_cross_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p25_cross_accuracy,
            CAST(0 AS DECIMAL(10,2)) as median_cross_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p75_cross_accuracy,
            CAST(0 AS DECIMAL(10,2)) as total_tackles_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_tackles_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_tackles_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as median_tackles_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_tackles_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as total_tackle_accuracy,
            CAST(0 AS DECIMAL(10,2)) as mean_tackle_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p25_tackle_accuracy,
            CAST(0 AS DECIMAL(10,2)) as median_tackle_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p75_tackle_accuracy,
            CAST(0 AS DECIMAL(10,2)) as total_pressures_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_pressures_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_pressures_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as median_pressures_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_pressures_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as total_pressures_completed_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_pressures_completed_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_pressures_completed_per90,
            CAST(0 AS DECIMAL(10,2)) as median_pressures_completed_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_pressures_completed_per90,
            CAST(0 AS DECIMAL(10,2)) as total_possession_won_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_possession_won_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_possession_won_per90,
            CAST(0 AS DECIMAL(10,2)) as median_possession_won_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_possession_won_per90,
            CAST(0 AS DECIMAL(10,2)) as total_possession_lost_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_possession_lost_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_possession_lost_per90,
            CAST(0 AS DECIMAL(10,2)) as median_possession_lost_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_possession_lost_per90,
            CAST(0 AS DECIMAL(10,2)) as total_key_tackles_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_key_tackles_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_key_tackles_per90,
            CAST(0 AS DECIMAL(10,2)) as median_key_tackles_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_key_tackles_per90,
            CAST(0 AS DECIMAL(10,2)) as total_interceptions_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_interceptions_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_interceptions_per90,
            CAST(0 AS DECIMAL(10,2)) as median_interceptions_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_interceptions_per90,
            CAST(0 AS DECIMAL(10,2)) as total_clearances_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_clearances_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_clearances_per90,
            CAST(0 AS DECIMAL(10,2)) as median_clearances_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_clearances_per90,
            CAST(0 AS DECIMAL(10,2)) as total_blocks_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_blocks_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_blocks_per90,
            CAST(0 AS DECIMAL(10,2)) as median_blocks_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_blocks_per90,
            CAST(0 AS DECIMAL(10,2)) as total_shots_blocked_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_shots_blocked_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_shots_blocked_per90,
            CAST(0 AS DECIMAL(10,2)) as median_shots_blocked_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_shots_blocked_per90,
            CAST(0 AS DECIMAL(10,2)) as total_headers_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_headers_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_headers_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as median_headers_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_headers_attempted_per90,
            CAST(0 AS DECIMAL(10,2)) as total_heading_accuracy,
            CAST(0 AS DECIMAL(10,2)) as mean_heading_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p25_heading_accuracy,
            CAST(0 AS DECIMAL(10,2)) as median_heading_accuracy,
            CAST(0 AS DECIMAL(10,2)) as p75_heading_accuracy,
            CAST(0 AS DECIMAL(10,2)) as total_key_headers_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_key_headers_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_key_headers_per90,
            CAST(0 AS DECIMAL(10,2)) as median_key_headers_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_key_headers_per90,
            CAST(0 AS DECIMAL(10,2)) as total_sprints_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_sprints_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_sprints_per90,
            CAST(0 AS DECIMAL(10,2)) as median_sprints_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_sprints_per90,
            CAST(0 AS DECIMAL(10,2)) as total_distance_covered_km_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_distance_covered_km_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_distance_covered_km_per90,
            CAST(0 AS DECIMAL(10,2)) as median_distance_covered_km_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_distance_covered_km_per90,
            CAST(0 AS DECIMAL(10,2)) as total_mistakes_leading_to_goals_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_mistakes_leading_to_goals_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_mistakes_leading_to_goals_per90,
            CAST(0 AS DECIMAL(10,2)) as median_mistakes_leading_to_goals_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_mistakes_leading_to_goals_per90,
            CAST(0 AS DECIMAL(10,2)) as total_fouls_made_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_fouls_made_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_fouls_made_per90,
            CAST(0 AS DECIMAL(10,2)) as median_fouls_made_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_fouls_made_per90,
            CAST(0 AS DECIMAL(10,2)) as total_fouls_against_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_fouls_against_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_fouls_against_per90,
            CAST(0 AS DECIMAL(10,2)) as median_fouls_against_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_fouls_against_per90,
            CAST(0 AS DECIMAL(10,2)) as total_yellow_cards_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_yellow_cards_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_yellow_cards_per90,
            CAST(0 AS DECIMAL(10,2)) as median_yellow_cards_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_yellow_cards_per90,
            CAST(0 AS DECIMAL(10,2)) as total_red_cards_per90,
            CAST(0 AS DECIMAL(10,2)) as mean_red_cards_per90,
            CAST(0 AS DECIMAL(10,2)) as p25_red_cards_per90,
            CAST(0 AS DECIMAL(10,2)) as median_red_cards_per90,
            CAST(0 AS DECIMAL(10,2)) as p75_red_cards_per90
        INTO gold.fact_positional_benchmarks
        FROM silver.dim_team_info AS A
        INNER JOIN silver.fact_outfield_player_stats AS B ON A.team_key = B.team_key
        INNER JOIN silver.dim_player_info AS C ON B.player_key = C.player_key
        WHERE 1 = 0; 
            
            PRINT '>>> Schema created successfully.';

        PRINT '>>> Truncating gold.fact_positional_benchmarks...';
        TRUNCATE TABLE gold.fact_positional_benchmarks;

        PRINT '>>> Calculating Benchmarks & Inserting New Records...';
        INSERT INTO gold.fact_positional_benchmarks
        SELECT DISTINCT
            A.team_key,
            A.league,
            A.club_name,
            C.position,
            SUM(B.minutes_played) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_minutes_played,
            AVG(B.minutes_played) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_minutes_played,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.minutes_played) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_minutes_played,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.minutes_played) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_minutes_played,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.minutes_played) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_minutes_played,
            SUM(B.team_goals_scored_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_team_goals_scored_per90,
            AVG(B.team_goals_scored_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_team_goals_scored_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.team_goals_scored_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_team_goals_scored_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.team_goals_scored_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_team_goals_scored_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.team_goals_scored_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_team_goals_scored_per90,
            SUM(B.team_goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_team_goals_conceded_per90,
            AVG(B.team_goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_team_goals_conceded_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.team_goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_team_goals_conceded_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.team_goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_team_goals_conceded_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.team_goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_team_goals_conceded_per90,
            SUM(B.goals) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_goals,
            AVG(B.goals) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_goals,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.goals) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_goals,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.goals) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_goals,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.goals) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_goals,
            SUM(B.goals_outside_the_box) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_goals_outside_the_box,
            AVG(B.goals_outside_the_box) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_goals_outside_the_box,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.goals_outside_the_box) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_goals_outside_the_box,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.goals_outside_the_box) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_goals_outside_the_box,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.goals_outside_the_box) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_goals_outside_the_box,
            SUM(B.shots_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_shots_per90,
            AVG(B.shots_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_shots_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.shots_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_shots_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.shots_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_shots_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.shots_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_shots_per90,
            SUM(B.xGoals_per_shot) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_xGoals_per_shot,
            AVG(B.xGoals_per_shot) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_xGoals_per_shot,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.xGoals_per_shot) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_xGoals_per_shot,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.xGoals_per_shot) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_xGoals_per_shot,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.xGoals_per_shot) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_xGoals_per_shot,
            AVG(B.shot_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_shot_accuracy,
            AVG(B.shot_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_shot_accuracy,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.shot_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_shot_accuracy,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.shot_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_shot_accuracy,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.shot_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_shot_accuracy,
            SUM(B.shots_on_target_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_shots_on_target_per90,
            AVG(B.shots_on_target_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_shots_on_target_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.shots_on_target_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_shots_on_target_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.shots_on_target_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_shots_on_target_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.shots_on_target_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_shots_on_target_per90,
            SUM(B.shots_outside_the_box_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_shots_outside_the_box_per90,
            AVG(B.shots_outside_the_box_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_shots_outside_the_box_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.shots_outside_the_box_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_shots_outside_the_box_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.shots_outside_the_box_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_shots_outside_the_box_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.shots_outside_the_box_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_shots_outside_the_box_per90,
            SUM(B.goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_goals_per90,
            AVG(B.goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_goals_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_goals_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_goals_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_goals_per90,
            SUM(B.xGoals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_xGoals_per90,
            AVG(B.xGoals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_xGoals_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.xGoals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_xGoals_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.xGoals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_xGoals_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.xGoals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_xGoals_per90,
            SUM(B.non_penalty_xGoals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_non_penalty_xGoals_per90,
            AVG(B.non_penalty_xGoals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_non_penalty_xGoals_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.non_penalty_xGoals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_non_penalty_xGoals_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.non_penalty_xGoals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_non_penalty_xGoals_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.non_penalty_xGoals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_non_penalty_xGoals_per90,
            SUM(B.xGoals_overperformance) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_xGoals_overperformance,
            AVG(B.xGoals_overperformance) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_xGoals_overperformance,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.xGoals_overperformance) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_xGoals_overperformance,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.xGoals_overperformance) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_xGoals_overperformance,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.xGoals_overperformance) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_xGoals_overperformance,
            AVG(B.conversion_rate) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_conversion_rate,
            AVG(B.conversion_rate) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_conversion_rate,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.conversion_rate) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_conversion_rate,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.conversion_rate) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_conversion_rate,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.conversion_rate) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_conversion_rate,
            SUM(B.assists) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_assists,
            AVG(B.assists) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_assists,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.assists) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_assists,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.assists) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_assists,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.assists) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_assists,
            SUM(B.assists_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_assists_per90,
            AVG(B.assists_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_assists_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.assists_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_assists_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.assists_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_assists_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.assists_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_assists_per90,
            SUM(B.passes_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_passes_attempted_per90,
            AVG(B.passes_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_passes_attempted_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.passes_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_passes_attempted_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.passes_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_passes_attempted_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.passes_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_passes_attempted_per90,
            AVG(B.pass_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_pass_accuracy,
            AVG(B.pass_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_pass_accuracy,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.pass_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_pass_accuracy,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.pass_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_pass_accuracy,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.pass_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_pass_accuracy,
            SUM(B.xAssits_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_xAssits_per90,
            AVG(B.xAssits_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_xAssits_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.xAssits_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_xAssits_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.xAssits_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_xAssits_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.xAssits_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_xAssits_per90,
            SUM(B.open_play_key_passes_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_open_play_key_passes_per90,
            AVG(B.open_play_key_passes_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_open_play_key_passes_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.open_play_key_passes_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_open_play_key_passes_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.open_play_key_passes_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_open_play_key_passes_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.open_play_key_passes_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_open_play_key_passes_per90,
            SUM(B.chances_created_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_chances_created_per90,
            AVG(B.chances_created_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_chances_created_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.chances_created_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_chances_created_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.chances_created_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_chances_created_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.chances_created_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_chances_created_per90,
            SUM(B.dribbles_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_dribbles_made_per90,
            AVG(B.dribbles_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_dribbles_made_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.dribbles_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_dribbles_made_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.dribbles_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_dribbles_made_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.dribbles_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_dribbles_made_per90,
            SUM(B.progressive_passes_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_progressive_passes_per90,
            AVG(B.progressive_passes_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_progressive_passes_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.progressive_passes_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_progressive_passes_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.progressive_passes_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_progressive_passes_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.progressive_passes_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_progressive_passes_per90,
            SUM(B.open_play_crosses_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_open_play_crosses_attempted_per90,
            AVG(B.open_play_crosses_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_open_play_crosses_attempted_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.open_play_crosses_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_open_play_crosses_attempted_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.open_play_crosses_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_open_play_crosses_attempted_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.open_play_crosses_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_open_play_crosses_attempted_per90,
            AVG(B.open_play_cross_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_open_play_cross_accuracy,
            AVG(B.open_play_cross_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_open_play_cross_accuracy,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.open_play_cross_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_open_play_cross_accuracy,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.open_play_cross_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_open_play_cross_accuracy,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.open_play_cross_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_open_play_cross_accuracy,
            SUM(B.crosses_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_crosses_attempted_per90,
            AVG(B.crosses_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_crosses_attempted_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.crosses_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_crosses_attempted_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.crosses_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_crosses_attempted_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.crosses_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_crosses_attempted_per90,
            AVG(B.cross_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_cross_accuracy,
            AVG(B.cross_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_cross_accuracy,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.cross_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_cross_accuracy,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.cross_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_cross_accuracy,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.cross_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_cross_accuracy,
            SUM(B.tackles_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_tackles_attempted_per90,
            AVG(B.tackles_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_tackles_attempted_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.tackles_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_tackles_attempted_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.tackles_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_tackles_attempted_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.tackles_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_tackles_attempted_per90,
            AVG(B.tackle_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_tackle_accuracy,
            AVG(B.tackle_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_tackle_accuracy,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.tackle_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_tackle_accuracy,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.tackle_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_tackle_accuracy,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.tackle_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_tackle_accuracy,
            SUM(B.pressures_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_pressures_attempted_per90,
            AVG(B.pressures_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_pressures_attempted_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.pressures_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_pressures_attempted_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.pressures_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_pressures_attempted_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.pressures_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_pressures_attempted_per90,
            SUM(B.pressures_completed_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_pressures_completed_per90,
            AVG(B.pressures_completed_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_pressures_completed_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.pressures_completed_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_pressures_completed_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.pressures_completed_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_pressures_completed_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.pressures_completed_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_pressures_completed_per90,
            SUM(B.possession_won_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_possession_won_per90,
            AVG(B.possession_won_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_possession_won_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.possession_won_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_possession_won_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.possession_won_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_possession_won_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.possession_won_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_possession_won_per90,
            SUM(B.possession_lost_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_possession_lost_per90,
            AVG(B.possession_lost_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_possession_lost_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.possession_lost_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_possession_lost_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.possession_lost_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_possession_lost_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.possession_lost_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_possession_lost_per90,
            SUM(B.key_tackles_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_key_tackles_per90,
            AVG(B.key_tackles_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_key_tackles_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.key_tackles_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_key_tackles_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.key_tackles_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_key_tackles_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.key_tackles_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_key_tackles_per90,
            SUM(B.interceptions_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_interceptions_per90,
            AVG(B.interceptions_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_interceptions_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.interceptions_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_interceptions_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.interceptions_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_interceptions_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.interceptions_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_interceptions_per90,
            SUM(B.clearances_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_clearances_per90,
            AVG(B.clearances_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_clearances_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.clearances_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_clearances_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.clearances_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_clearances_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.clearances_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_clearances_per90,
            SUM(B.blocks_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_blocks_per90,
            AVG(B.blocks_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_blocks_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.blocks_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_blocks_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.blocks_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_blocks_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.blocks_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_blocks_per90,
            SUM(B.shots_blocked_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_shots_blocked_per90,
            AVG(B.shots_blocked_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_shots_blocked_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.shots_blocked_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_shots_blocked_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.shots_blocked_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_shots_blocked_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.shots_blocked_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_shots_blocked_per90,
            SUM(B.headers_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_headers_attempted_per90,
            AVG(B.headers_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_headers_attempted_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.headers_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_headers_attempted_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.headers_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_headers_attempted_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.headers_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_headers_attempted_per90,
            AVG(B.heading_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_heading_accuracy,
            AVG(B.heading_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_heading_accuracy,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.heading_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_heading_accuracy,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.heading_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_heading_accuracy,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.heading_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_heading_accuracy,
            SUM(B.key_headers_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_key_headers_per90,
            AVG(B.key_headers_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_key_headers_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.key_headers_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_key_headers_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.key_headers_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_key_headers_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.key_headers_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_key_headers_per90,
            SUM(B.sprints_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_sprints_per90,
            AVG(B.sprints_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_sprints_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.sprints_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_sprints_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.sprints_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_sprints_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.sprints_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_sprints_per90,
            SUM(B.distance_covered_km_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_distance_covered_km_per90,
            AVG(B.distance_covered_km_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_distance_covered_km_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.distance_covered_km_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_distance_covered_km_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.distance_covered_km_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_distance_covered_km_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.distance_covered_km_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_distance_covered_km_per90,
            SUM(B.mistakes_leading_to_goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_mistakes_leading_to_goals_per90,
            AVG(B.mistakes_leading_to_goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_mistakes_leading_to_goals_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.mistakes_leading_to_goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_mistakes_leading_to_goals_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.mistakes_leading_to_goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_mistakes_leading_to_goals_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.mistakes_leading_to_goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_mistakes_leading_to_goals_per90,
            SUM(B.fouls_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_fouls_made_per90,
            AVG(B.fouls_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_fouls_made_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.fouls_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_fouls_made_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.fouls_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_fouls_made_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.fouls_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_fouls_made_per90,
            SUM(B.fouls_against_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_fouls_against_per90,
            AVG(B.fouls_against_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_fouls_against_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.fouls_against_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_fouls_against_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.fouls_against_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_fouls_against_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.fouls_against_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_fouls_against_per90,
            SUM(B.yellow_cards_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_yellow_cards_per90,
            AVG(B.yellow_cards_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_yellow_cards_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.yellow_cards_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_yellow_cards_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.yellow_cards_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_yellow_cards_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.yellow_cards_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_yellow_cards_per90,
            SUM(B.red_cards_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS total_red_cards_per90,
            AVG(B.red_cards_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS mean_red_cards_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.red_cards_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p25_red_cards_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.red_cards_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS median_red_cards_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.red_cards_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name, C.position) AS p75_red_cards_per90
        FROM silver.dim_team_info AS A
        INNER JOIN silver.fact_outfield_player_stats AS B
            ON A.team_key = B.team_key
        INNER JOIN silver.dim_player_info AS C
            ON B.player_key = C.player_key
        WHERE A.dwh_current_validity = 1;

        SET @end_time = GETDATE();
        PRINT '===================================================';
        PRINT 'LOADING COMPLETED';
        PRINT 'DURATION: ' + CAST(DATEDIFF(millisecond, @start_time, @end_time) AS NVARCHAR) + ' milliseconds';
        PRINT '===================================================';

--GOLD.FACT_GK_BENCHMARKS
        PRINT '=============================================';
        PRINT 'GOLD.FACT_GK_BENCHMARKS';
        PRINT '---------------------------------------------';
        PRINT 'LOADING DATA FROM: silver.fact_gk_stats';
        PRINT 'LOADING DATA FROM: silver.dim_player_info';
        PRINT 'LOADING DATA FROM: silver.dim_team_info';
        PRINT '---------------------------------------------';
        SET @start_time = GETDATE();
        IF OBJECT_ID('gold.fact_gk_benchmarks', 'U') IS NULL
        PRINT '>>> Target table does not exist. Auto-generating schema...';
        SELECT TOP 0
            A.team_key,
            A.league,
            A.club_name,
            CAST(0 AS INT) as total_minutes_played,
            CAST(0 AS DECIMAL(10, 2)) as mean_minutes_played,
            CAST(0 AS DECIMAL(10, 2)) as p25_minutes_played,
            CAST(0 AS DECIMAL(10, 2)) as median_minutes_played,
            CAST(0 AS DECIMAL(10, 2)) as p75_minutes_played,
            CAST(0 AS DECIMAL(10, 2)) as total_team_goals_scored_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_team_goals_scored_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_team_goals_scored_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_team_goals_scored_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_team_goals_scored_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_team_goals_conceded_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_team_goals_conceded_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_team_goals_conceded_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_team_goals_conceded_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_team_goals_conceded_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_goals_conceded_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_goals_conceded_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_goals_conceded_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_goals_conceded_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_goals_conceded_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_saves_made_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_saves_made_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_saves_made_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_saves_made_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_saves_made_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_xGoals_prevented_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_xGoals_prevented_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_xGoals_prevented_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_xGoals_prevented_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_xGoals_prevented_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_xSave_rate,
            CAST(0 AS DECIMAL(10, 2)) as mean_xSave_rate,
            CAST(0 AS DECIMAL(10, 2)) as p25_xSave_rate,
            CAST(0 AS DECIMAL(10, 2)) as median_xSave_rate,
            CAST(0 AS DECIMAL(10, 2)) as p75_xSave_rate,
            CAST(0 AS DECIMAL(10, 2)) as total_saves_tipped_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_saves_tipped_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_saves_tipped_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_saves_tipped_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_saves_tipped_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_saves_parried_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_saves_parried_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_saves_parried_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_saves_parried_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_saves_parried_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_saves_held_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_saves_held_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_saves_held_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_saves_held_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_saves_held_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_saves_percentage,
            CAST(0 AS DECIMAL(10, 2)) as mean_saves_percentage,
            CAST(0 AS DECIMAL(10, 2)) as p25_saves_percentage,
            CAST(0 AS DECIMAL(10, 2)) as median_saves_percentage,
            CAST(0 AS DECIMAL(10, 2)) as p75_saves_percentage,
            CAST(0 AS DECIMAL(10, 2)) as total_passes_attempted_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_passes_attempted_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_passes_attempted_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_passes_attempted_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_passes_attempted_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_pass_accuracy,
            CAST(0 AS DECIMAL(10, 2)) as mean_pass_accuracy,
            CAST(0 AS DECIMAL(10, 2)) as p25_pass_accuracy,
            CAST(0 AS DECIMAL(10, 2)) as median_pass_accuracy,
            CAST(0 AS DECIMAL(10, 2)) as p75_pass_accuracy,
            CAST(0 AS DECIMAL(10, 2)) as total_possession_won_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_possession_won_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_possession_won_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_possession_won_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_possession_won_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_possession_lost_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_possession_lost_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_possession_lost_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_possession_lost_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_possession_lost_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_interceptions_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_interceptions_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_interceptions_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_interceptions_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_interceptions_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_clearances_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_clearances_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_clearances_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_clearances_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_clearances_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_penalties_faced_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_penalties_faced_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_penalties_faced_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_penalties_faced_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_penalties_faced_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_penalties_save_percentage,
            CAST(0 AS DECIMAL(10, 2)) as mean_penalties_save_percentage,
            CAST(0 AS DECIMAL(10, 2)) as p25_penalties_save_percentage,
            CAST(0 AS DECIMAL(10, 2)) as median_penalties_save_percentage,
            CAST(0 AS DECIMAL(10, 2)) as p75_penalties_save_percentage,
            CAST(0 AS DECIMAL(10, 2)) as total_distance_covered_km_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_distance_covered_km_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_distance_covered_km_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_distance_covered_km_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_distance_covered_km_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_mistakes_leading_to_goals_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_mistakes_leading_to_goals_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_mistakes_leading_to_goals_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_mistakes_leading_to_goals_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_mistakes_leading_to_goals_per90,
            CAST(0 AS DECIMAL(10, 2)) as total_fouls_against_per90,
            CAST(0 AS DECIMAL(10, 2)) as mean_fouls_against_per90,
            CAST(0 AS DECIMAL(10, 2)) as p25_fouls_against_per90,
            CAST(0 AS DECIMAL(10, 2)) as median_fouls_against_per90,
            CAST(0 AS DECIMAL(10, 2)) as p75_fouls_against_per90
        INTO gold.fact_gk_benchmarks
        FROM silver.dim_team_info AS A
        INNER JOIN silver.fact_gk_stats AS B ON A.team_key = B.team_key
        WHERE 1 = 0;
            
            PRINT '>>> Schema created successfully.';

        PRINT '>>> Truncating gold.fact_gk_benchmarks...';
        TRUNCATE TABLE gold.fact_gk_benchmarks;

        PRINT '>>> Calculating GK Benchmarks & Inserting New Records...';
        INSERT INTO gold.fact_gk_benchmarks
        SELECT DISTINCT
            A.team_key,
            A.league,
            A.club_name,
            SUM(B.minutes_played) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_minutes_played,
            AVG(B.minutes_played) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_minutes_played,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.minutes_played) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_minutes_played,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.minutes_played) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_minutes_played,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.minutes_played) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_minutes_played,
            SUM(B.team_goals_scored_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_team_goals_scored_per90,
            AVG(B.team_goals_scored_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_team_goals_scored_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.team_goals_scored_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_team_goals_scored_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.team_goals_scored_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_team_goals_scored_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.team_goals_scored_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_team_goals_scored_per90,
            SUM(B.team_goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_team_goals_conceded_per90,
            AVG(B.team_goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_team_goals_conceded_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.team_goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_team_goals_conceded_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.team_goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_team_goals_conceded_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.team_goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_team_goals_conceded_per90,
            SUM(B.goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_goals_conceded_per90,
            AVG(B.goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_goals_conceded_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_goals_conceded_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_goals_conceded_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.goals_conceded_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_goals_conceded_per90,
            SUM(B.saves_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_saves_made_per90,
            AVG(B.saves_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_saves_made_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.saves_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_saves_made_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.saves_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_saves_made_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.saves_made_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_saves_made_per90,
            SUM(B.xGoals_prevented_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_xGoals_prevented_per90,
            AVG(B.xGoals_prevented_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_xGoals_prevented_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.xGoals_prevented_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_xGoals_prevented_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.xGoals_prevented_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_xGoals_prevented_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.xGoals_prevented_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_xGoals_prevented_per90,
            AVG(B.xSave_rate) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_xSave_rate,
            AVG(B.xSave_rate) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_xSave_rate,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.xSave_rate) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_xSave_rate,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.xSave_rate) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_xSave_rate,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.xSave_rate) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_xSave_rate,
            SUM(B.saves_tipped_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_saves_tipped_per90,
            AVG(B.saves_tipped_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_saves_tipped_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.saves_tipped_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_saves_tipped_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.saves_tipped_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_saves_tipped_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.saves_tipped_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_saves_tipped_per90,
            SUM(B.saves_parried_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_saves_parried_per90,
            AVG(B.saves_parried_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_saves_parried_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.saves_parried_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_saves_parried_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.saves_parried_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_saves_parried_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.saves_parried_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_saves_parried_per90,
            SUM(B.saves_held_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_saves_held_per90,
            AVG(B.saves_held_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_saves_held_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.saves_held_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_saves_held_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.saves_held_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_saves_held_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.saves_held_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_saves_held_per90,
            AVG(B.saves_percentage) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_saves_percentage,
            AVG(B.saves_percentage) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_saves_percentage,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.saves_percentage) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_saves_percentage,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.saves_percentage) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_saves_percentage,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.saves_percentage) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_saves_percentage,
            SUM(B.passes_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_passes_attempted_per90,
            AVG(B.passes_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_passes_attempted_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.passes_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_passes_attempted_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.passes_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_passes_attempted_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.passes_attempted_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_passes_attempted_per90,
            AVG(B.pass_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_pass_accuracy,
            AVG(B.pass_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_pass_accuracy,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.pass_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_pass_accuracy,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.pass_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_pass_accuracy,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.pass_accuracy) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_pass_accuracy,
            SUM(B.possession_won_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_possession_won_per90,
            AVG(B.possession_won_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_possession_won_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.possession_won_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_possession_won_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.possession_won_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_possession_won_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.possession_won_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_possession_won_per90,
            SUM(B.possession_lost_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_possession_lost_per90,
            AVG(B.possession_lost_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_possession_lost_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.possession_lost_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_possession_lost_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.possession_lost_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_possession_lost_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.possession_lost_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_possession_lost_per90,
            SUM(B.interceptions_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_interceptions_per90,
            AVG(B.interceptions_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_interceptions_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.interceptions_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_interceptions_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.interceptions_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_interceptions_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.interceptions_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_interceptions_per90,
            SUM(B.clearances_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_clearances_per90,
            AVG(B.clearances_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_clearances_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.clearances_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_clearances_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.clearances_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_clearances_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.clearances_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_clearances_per90,
            SUM(B.penalties_faced_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_penalties_faced_per90,
            AVG(B.penalties_faced_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_penalties_faced_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.penalties_faced_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_penalties_faced_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.penalties_faced_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_penalties_faced_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.penalties_faced_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_penalties_faced_per90,
            AVG(B.penalties_save_percentage) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_penalties_save_percentage,
            AVG(B.penalties_save_percentage) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_penalties_save_percentage,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.penalties_save_percentage) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_penalties_save_percentage,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.penalties_save_percentage) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_penalties_save_percentage,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.penalties_save_percentage) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_penalties_save_percentage,
            SUM(B.distance_covered_km_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_distance_covered_km_per90,
            AVG(B.distance_covered_km_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_distance_covered_km_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.distance_covered_km_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_distance_covered_km_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.distance_covered_km_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_distance_covered_km_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.distance_covered_km_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_distance_covered_km_per90,
            SUM(B.mistakes_leading_to_goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_mistakes_leading_to_goals_per90,
            AVG(B.mistakes_leading_to_goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_mistakes_leading_to_goals_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.mistakes_leading_to_goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_mistakes_leading_to_goals_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.mistakes_leading_to_goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_mistakes_leading_to_goals_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.mistakes_leading_to_goals_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_mistakes_leading_to_goals_per90,
            SUM(B.fouls_against_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS total_fouls_against_per90,
            AVG(B.fouls_against_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS mean_fouls_against_per90,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY B.fouls_against_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p25_fouls_against_per90,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY B.fouls_against_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS median_fouls_against_per90,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY B.fouls_against_per90) OVER (PARTITION BY A.team_key, A.league, A.club_name) AS p75_fouls_against_per90
        FROM silver.dim_team_info AS A
        INNER JOIN silver.fact_gk_stats AS B
            ON A.team_key = B.team_key
        WHERE A.dwh_current_validity = 1;

        SET @end_time = GETDATE();
        PRINT '---------------------------------------------';
        PRINT '>>DURATION: ' + CAST(DATEDIFF(millisecond, @start_time, @end_time) AS NVARCHAR) + ' milliseconds';
        PRINT '---------------------------------------------';

        SET @batch_end_time = GETDATE();
        PRINT '=================================';
        PRINT 'LOADING OF GOLD LAYER COMPLETED';
        PRINT 'TOTAL DURATION: ' + CAST(DATEDIFF(millisecond, @batch_start_time, @batch_end_time) AS NVARCHAR) + ' milliseconds';
        PRINT '=================================';
    END TRY
    BEGIN CATCH
        PRINT '=================================';
        PRINT 'ERROR DURING LOADING GOLD BENCHMARKS';
        PRINT 'Error Message:' + ERROR_MESSAGE();
        PRINT 'Error Message:' + CAST(ERROR_NUMBER() AS NVARCHAR);
        PRINT 'Error Message:' + CAST(ERROR_STATE() AS NVARCHAR);
        PRINT '=================================';
    END CATCH
END